# Generated by Django 5.0.1 on 2025-03-27 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='year',
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('faculty_type', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=10)),
                ('students', models.ManyToManyField(related_name='studies_in', to='student.student')),
                ('class_incharge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='incharge_of', to='student.faculty')),
                ('faculties', models.ManyToManyField(related_name='handles', to='student.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='faculty_OD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ODs', to='student.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='student_OD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=50)),
                ('eventType', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=50)),
                ('proof', models.FileField(blank=True, null=True, upload_to='proofs/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('isTeam', models.BooleanField(default=False)),
                ('mentor_approval', models.BooleanField(default=False)),
                ('class_incharge_approval', models.BooleanField(default=False)),
                ('OD_rejection', models.BooleanField(default=False)),
                ('academic_head_approval', models.BooleanField(default=False)),
                ('hod_approval', models.BooleanField(default=False)),
                ('ClassOf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ODs', to='student.class')),
                ('class_incharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OD_to_be_approve', to='student.faculty')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentors', to='student.faculty')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ODs', to='student.student')),
            ],
        ),
    ]
