# Generated by Django 5.0.1 on 2025-03-28 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_department_remove_student_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='faculty_type',
        ),
    ]
