# Generated by Django 5.0.1 on 2025-03-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_faculty_faculty_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='faculty_type',
            field=models.CharField(choices=[('HOD', 'HOD'), ('Teaching', 'Teaching'), ('Academic Head', 'Academic Head'), ('DC', 'DC')], default='Teaching', max_length=20),
        ),
    ]
