# Generated by Django 5.0.1 on 2025-04-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_faculty_faculty_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='faculty_code',
            field=models.CharField(default=123, max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_type',
            field=models.CharField(choices=[('HOD', 'HOD'), ('Teaching', 'Teaching'), ('Academic Head 1st Year', 'Academic Head 1st Year'), ('Academic Head 2nd Year', 'Academic Head 2nd Year'), ('Academic Head 3rd Year', 'Academic Head 3rd Year'), ('DC', 'DC')], default='Teaching', max_length=50),
        ),
    ]
