# Generated by Django 5.0.1 on 2025-04-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_faculty_faculty_code_alter_faculty_faculty_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(default='CSE', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.IntegerField(default='2', max_length=10),
        ),
    ]
