# Generated by Django 5.0.1 on 2025-04-02 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_student_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_od',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='student_od',
            name='mentor_approval',
        ),
        migrations.AddField(
            model_name='student_od',
            name='teammates',
            field=models.ManyToManyField(blank=True, related_name='teammates', to='student.student'),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=10, unique=True)),
                ('department', models.CharField(default='CSE', max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
