# Generated by Django 5.0.1 on 2025-04-02 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_remove_student_od_mentor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
