# Generated by Django 5.0.1 on 2025-04-06 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_delete_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_incharge',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incharge_of', to='student.faculty'),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(default='2'),
        ),
    ]
